export const subscribe = [
  { email: 'lucas.fernandez92@gmail.com' },
  { email: 'marisol.rojas87@gmail.com' },
  { email: 'andres.tec.dev@gmail.com' },
  { email: 'camila_estrella21@gmail.com' },
  { email: 'juanma.codes@gmail.com' },
  { email: 'natalia.writer99@gmail.com' },
  { email: 'leo.desingart@gmail.com' },
  { email: 'sofia.devweb@gmail.com' },
  { email: 'tomas.creativo88@gmail.com' },
  { email: 'vale.ideaspro@gmail.com' },
];

export const category = [
  { nameCategory: 'Refrescos' },
  { nameCategory: 'Cerveza' },
  { nameCategory: 'Singani' },
  { nameCategory: 'Energizantes' },
  { nameCategory: 'Snacks' },
];

export const products = [
  {
    nameProduct: 'Coca-Cola 2L',
    imageProduct:
      'https://farmacorp.com/cdn/shop/files/909699_1200x1200.jpg?v=1714434898',
    price: 8,
    stock: 60,
  },
  {
    nameProduct: 'Pepsi 3L',
    imageProduct: 'https://laoferta.cl/wp-content/images/17878-1.jpg',
    price: 12,
    stock: 36,
  },
  {
    nameProduct: 'Salvietti Papaya 2L',
    imageProduct:
      'https://salvietti.com.bo/wp-content/uploads/2020/12/enano-quienes-somos.png',
    price: 10,
    stock: 36,
  },
  {
    nameProduct: 'Fanta Naranja 2L',
    imageProduct: 'https://images.fanta.com/product-image.png',
    price: 9,
    stock: 40,
  },
  {
    nameProduct: 'Sprite 2L',
    imageProduct: 'https://images.sprite.com/product-image.png',
    price: 8,
    stock: 38,
  },
  {
    nameProduct: '7up 2.25L',
    imageProduct: 'https://7up.com.bo/product-image.jpg',
    price: 9,
    stock: 35,
  },
  {
    nameProduct: 'Coca-Cola Sin Azúcar 2L',
    imageProduct: 'https://farmacorp.com/cdn/shop/files/coca-zero.jpg',
    price: 8,
    stock: 20,
  },
  {
    nameProduct: 'Pepsi Black 2L',
    imageProduct: 'https://pepsi.com.bo/black.jpg',
    price: 10,
    stock: 15,
  },
  {
    nameProduct: 'Fanta Uva 2L',
    imageProduct: 'https://fanta.com.bo/uva.jpg',
    price: 9,
    stock: 18,
  },
  {
    nameProduct: 'Sprite Zero 2L',
    imageProduct: 'https://sprite.com.bo/zero.jpg',
    price: 8,
    stock: 12,
  },
  {
    nameProduct: 'Guaraná Antarctica 2L',
    imageProduct: 'https://guarana.com/product-image.jpg',
    price: 11,
    stock: 30,
  },
  {
    nameProduct: 'Coca-Cola 500ml',
    imageProduct: 'https://coca.com.bo/500.jpg',
    price: 5,
    stock: 80,
  },
  {
    nameProduct: 'Pepsi 500ml',
    imageProduct: 'https://pepsi.com.bo/500.jpg',
    price: 5,
    stock: 70,
  },
  {
    nameProduct: 'Sprite 500ml',
    imageProduct: 'https://sprite.com.bo/500.jpg',
    price: 5,
    stock: 60,
  },
  {
    nameProduct: 'Fanta 500ml',
    imageProduct: 'https://fanta.com.bo/500.jpg',
    price: 5,
    stock: 40,
  },
  {
    nameProduct: 'Salvietti Manzana 2L',
    imageProduct: 'https://salvietti.com.bo/manzana.jpg',
    price: 10,
    stock: 33,
  },
  {
    nameProduct: 'Agua Vital 2L',
    imageProduct: 'https://aguavital.com.bo/2l.jpg',
    price: 6,
    stock: 50,
  },
  {
    nameProduct: 'Agua Cielo 2L',
    imageProduct: 'https://aguacielo.com/product.jpg',
    price: 6,
    stock: 50,
  },
  {
    nameProduct: 'Fioravanti Frutilla 2L',
    imageProduct: 'https://fioravanti.com/frutilla.jpg',
    price: 9,
    stock: 25,
  },
  {
    nameProduct: 'Fioravanti Uva 2L',
    imageProduct: 'https://fioravanti.com/uva.jpg',
    price: 9,
    stock: 25,
  },
  {
    nameProduct: 'Sinalco 2L',
    imageProduct: 'https://sinalco.com.bo/2l.jpg',
    price: 8,
    stock: 20,
  },
  {
    nameProduct: 'Sinalco Limón 2L',
    imageProduct: 'https://sinalco.com.bo/limon.jpg',
    price: 8,
    stock: 20,
  },
  {
    nameProduct: 'Orange Crush 2L',
    imageProduct: 'https://crush.com/orange.jpg',
    price: 9,
    stock: 15,
  },
  {
    nameProduct: 'Soda Sayon 2L',
    imageProduct: 'https://sayon.com.bo/soda.jpg',
    price: 7,
    stock: 30,
  },
  {
    nameProduct: 'Coca-Cola Light 2L',
    imageProduct: 'https://coca.com.bo/light.jpg',
    price: 8,
    stock: 25,
  },

  // CERVEZA (20)
  {
    nameProduct: 'Paceña 620ml',
    imageProduct:
      'https://www.agavemicromercado.com/wp-content/uploads/6CBN-PACE-Cerv-620ml.jpg',
    price: 15,
    stock: 65,
  },
  {
    nameProduct: 'Huari Negra 330ml',
    imageProduct:
      'https://www.fidalga.com/cdn/shop/products/9ad962b6-3d67-4ffa-b243-0720db397853.png?v=1653345084',
    price: 10,
    stock: 60,
  },
  {
    nameProduct: 'Corona 355ml',
    imageProduct:
      'https://www.fidalga.com/cdn/shop/products/0173769.jpg?v=1653343587',
    price: 12.5,
    stock: 30,
  },
  {
    nameProduct: 'Brahma 473ml',
    imageProduct: 'https://brahma.com.bo/lata.jpg',
    price: 10,
    stock: 50,
  },
  {
    nameProduct: 'Taquiña 330ml',
    imageProduct: 'https://taquina.com.bo/330.jpg',
    price: 9,
    stock: 35,
  },
  {
    nameProduct: 'Huari Tradicional 330ml',
    imageProduct: 'https://huari.com.bo/tradicional.jpg',
    price: 10,
    stock: 45,
  },
  {
    nameProduct: 'Potosina 330ml',
    imageProduct: 'https://potosina.com.bo/330.jpg',
    price: 9,
    stock: 40,
  },
  {
    nameProduct: 'Budweiser 355ml',
    imageProduct: 'https://budweiser.com/355.jpg',
    price: 13,
    stock: 30,
  },
  {
    nameProduct: 'Heineken 330ml',
    imageProduct: 'https://heineken.com/330.jpg',
    price: 14,
    stock: 30,
  },
  {
    nameProduct: 'Stella Artois 330ml',
    imageProduct: 'https://stellaartois.com/330.jpg',
    price: 15,
    stock: 25,
  },
  {
    nameProduct: 'Paceña Black 330ml',
    imageProduct: 'https://paceña.com.bo/black.jpg',
    price: 11,
    stock: 40,
  },
  {
    nameProduct: 'Bavaria 330ml',
    imageProduct: 'https://bavaria.com/330.jpg',
    price: 10,
    stock: 35,
  },
  {
    nameProduct: 'Quilmes 473ml',
    imageProduct: 'https://quilmes.com.ar/lata.jpg',
    price: 12,
    stock: 20,
  },
  {
    nameProduct: 'Cusqueña 330ml',
    imageProduct: 'https://cusquena.com.bo/330.jpg',
    price: 13,
    stock: 28,
  },
  {
    nameProduct: 'Becker 330ml',
    imageProduct: 'https://becker.com.bo/330.jpg',
    price: 9,
    stock: 22,
  },
  {
    nameProduct: 'Paceña Sin Alcohol 330ml',
    imageProduct: 'https://paceña.com.bo/sinalcohol.jpg',
    price: 8,
    stock: 18,
  },
  {
    nameProduct: 'Bud Light 355ml',
    imageProduct: 'https://budlight.com/355.jpg',
    price: 11,
    stock: 30,
  },
  {
    nameProduct: 'Aguila 330ml',
    imageProduct: 'https://aguila.com.bo/330.jpg',
    price: 10,
    stock: 27,
  },
  {
    nameProduct: 'Miller 355ml',
    imageProduct: 'https://miller.com.bo/355.jpg',
    price: 14,
    stock: 20,
  },
  {
    nameProduct: 'Corona Ligera 355ml',
    imageProduct: 'https://corona.com/ligera.jpg',
    price: 13,
    stock: 25,
  },

  // SINGANI (15)
  {
    nameProduct: 'Casa real tapa roja',
    imageProduct:
      'https://www.singanicasareal.com/wp-content/uploads/2024/01/Casa-Real-Pagina-Web-Banner-Etiqueta-Roja-710x1024-1.jpg',
    price: 90,
    stock: 12,
  },
  {
    nameProduct: 'Casa real tapa azul',
    imageProduct:
      'https://licorhouse.com/cdn/shop/products/0101-030750.jpg?v=1669294937',
    price: 120,
    stock: 18,
  },
  {
    nameProduct: 'Casa real tapa negra',
    imageProduct:
      'https://www.singanicasareal.com/wp-content/uploads/2019/07/singani-casa-real-15.png',
    price: 150,
    stock: 8,
  },
  {
    nameProduct: 'Los Parrales 750ml',
    imageProduct: 'https://losparrales.com.bo/750.jpg',
    price: 80,
    stock: 20,
  },
  {
    nameProduct: 'Rujero 750ml',
    imageProduct: 'https://rujero.com.bo/750.jpg',
    price: 95,
    stock: 18,
  },
  {
    nameProduct: 'Casa Grande 750ml',
    imageProduct: 'https://casagrande.com.bo/750.jpg',
    price: 100,
    stock: 10,
  },
  {
    nameProduct: 'El Potro 750ml',
    imageProduct: 'https://elpotro.com.bo/750.jpg',
    price: 70,
    stock: 15,
  },
  {
    nameProduct: 'Don Lucho 750ml',
    imageProduct: 'https://donlucho.com.bo/750.jpg',
    price: 85,
    stock: 15,
  },
  {
    nameProduct: 'Flor de Vid 750ml',
    imageProduct: 'https://flordevid.com.bo/750.jpg',
    price: 110,
    stock: 12,
  },
  {
    nameProduct: 'Singani San Pedro 750ml',
    imageProduct: 'https://sanpedro.com.bo/750.jpg',
    price: 95,
    stock: 13,
  },
  {
    nameProduct: 'San Remo 750ml',
    imageProduct: 'https://sanremo.com.bo/750.jpg',
    price: 90,
    stock: 10,
  },
  {
    nameProduct: 'Condeza 750ml',
    imageProduct: 'https://condeza.com.bo/750.jpg',
    price: 85,
    stock: 10,
  },
  {
    nameProduct: 'Don Alejandro 750ml',
    imageProduct: 'https://donalejandro.com.bo/750.jpg',
    price: 100,
    stock: 8,
  },
  {
    nameProduct: 'Flor de Vid Etiqueta Negra',
    imageProduct: 'https://flordevid.com.bo/black.jpg',
    price: 120,
    stock: 6,
  },
  {
    nameProduct: 'Singani Aranjuez',
    imageProduct: 'https://aranjuez.com.bo/750.jpg',
    price: 110,
    stock: 7,
  },

  // ENERGIZANTES (10)
  {
    nameProduct: 'Red Bull 250ml',
    imageProduct:
      'https://farmacorp.com/cdn/shop/files/564111_1200x1200.jpg?v=1714434386',
    price: 15,
    stock: 90,
  },
  {
    nameProduct: 'Monster Energy 473ml',
    imageProduct:
      'https://amarket.com.bo/cdn/shop/files/070847028406_700x700.jpg?v=1712344275',
    price: 20,
    stock: 12,
  },
  {
    nameProduct: 'Speed Unlimited',
    imageProduct:
      'https://www.distribuidorabebidas.com.uy/wp-content/uploads/sites/31/2018/01/speed-510x383.jpg',
    price: 6,
    stock: 18,
  },
  {
    nameProduct: 'Volt 500ml',
    imageProduct: 'https://volt.com.bo/500.jpg',
    price: 10,
    stock: 22,
  },
  {
    nameProduct: 'Gatorade Azul 500ml',
    imageProduct: 'https://gatorade.com.bo/azul.jpg',
    price: 9,
    stock: 30,
  },
  {
    nameProduct: 'Gatorade Naranja 500ml',
    imageProduct: 'https://gatorade.com.bo/naranja.jpg',
    price: 9,
    stock: 30,
  },
  {
    nameProduct: 'Monster Ultra 473ml',
    imageProduct: 'https://monster.com.bo/ultra.jpg',
    price: 20,
    stock: 10,
  },
  {
    nameProduct: 'Red Bull Zero 250ml',
    imageProduct: 'https://redbull.com/zero.jpg',
    price: 15,
    stock: 15,
  },
  {
    nameProduct: 'Vive 500ml',
    imageProduct: 'https://vive.com.bo/500.jpg',
    price: 8,
    stock: 20,
  },
  {
    nameProduct: 'Volt Zero 500ml',
    imageProduct: 'https://volt.com.bo/zero.jpg',
    price: 9,
    stock: 18,
  },

  // SNACKS (5)
  {
    nameProduct: 'Maní salado',
    imageProduct:
      'https://jumboargentina.vtexassets.com/arquivos/ids/788483/Man-Mani-King-Salado-Sin-Piel-X100g-1-976844.jpg?v=638253790004330000',
    price: 8,
    stock: 24,
  },
  {
    nameProduct: 'Papas fritas Lays clásicas',
    imageProduct:
      'https://icnorteb2c.vteximg.com.br/arquivos/ids/155917-600-600/Papas-Fritas-Clasicas-Lays-185-Gr-1-460.jpg?v=637345691513100000',
    price: 15,
    stock: 12,
  },
  {
    nameProduct: 'Chicharrón',
    imageProduct:
      'https://www.fidalga.com/cdn/shop/products/DSC02073.jpg?v=1653343622',
    price: 34,
    stock: 5,
  },
  {
    nameProduct: 'Doritos Queso',
    imageProduct: 'https://doritos.com/queso.jpg',
    price: 12,
    stock: 20,
  },
  {
    nameProduct: 'Piqueo Salado',
    imageProduct: 'https://piqueo.com.bo/salado.jpg',
    price: 10,
    stock: 18,
  },
];

export const level = [{ nameLevel: 'admin' }, { nameLevel: 'standar' }];

export const listUsers = [
  {
    name: 'Patito',
    lastName: 'Blade Truce',
    email: 'nena@gmail.com',
    carnet: '8954523',
    phone: 75850236,
    password: 'password123',
    profilePicture:
      'https://res.cloudinary.com/dqgcyonb9/image/upload/v1723172445/Ballet/qqapxmcvvceb2epa33mr.png',
  },
  {
    name: 'Nicolas',
    lastName: 'Choque Lopez',
    email: 'nico@gmail.com',
    carnet: '6548950',
    phone: 75693120,
    password: 'password123',
    profilePicture:
      'https://res.cloudinary.com/dqgcyonb9/image/upload/v1729092230/Ballet/ume76hsu8xbingqqa38w.png',
  },
  {
    name: 'Pipocas',
    lastName: 'Altamirano Morales',
    email: 'pipocas@gmail.com',
    carnet: '9856324',
    phone: 74123695,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Pelucas',
    lastName: 'Mendez Zapana',
    email: 'pelucas@gmail.com',
    carnet: '9820036',
    phone: 79613458,
    password: 'password123',
    profilePicture:
      'https://res.cloudinary.com/dqgcyonb9/image/upload/v1733339396/Ballet/dpcm66v7zsaexyxdusqu.png',
  },
  {
    name: 'Luna',
    lastName: 'Torrez Condori',
    email: 'luna@gmail.com',
    carnet: '7412569',
    phone: 71245896,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Carlos',
    lastName: 'Mamani Flores',
    email: 'carlos@gmail.com',
    carnet: '8712541',
    phone: 78963214,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Valentina',
    lastName: 'Soria Guzman',
    email: 'valen@gmail.com',
    carnet: '9012456',
    phone: 72145896,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Diego',
    lastName: 'Rojas Paredes',
    email: 'diego@gmail.com',
    carnet: '8912354',
    phone: 78451236,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Flor',
    lastName: 'Gonzales Romero',
    email: 'flor@gmail.com',
    carnet: '7458963',
    phone: 71589326,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Martin',
    lastName: 'Flores Quispe',
    email: 'martin@gmail.com',
    carnet: '8529631',
    phone: 79365821,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Camila',
    lastName: 'Rodriguez Vargas',
    email: 'camila@gmail.com',
    carnet: '7421596',
    phone: 78965412,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Joaquin',
    lastName: 'Vega Soto',
    email: 'joaquin@gmail.com',
    carnet: '8652147',
    phone: 78124563,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Luciana',
    lastName: 'Navarro Ruiz',
    email: 'luciana@gmail.com',
    carnet: '9047851',
    phone: 79251486,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Eduardo',
    lastName: 'Salinas Montaño',
    email: 'edu@gmail.com',
    carnet: '8913257',
    phone: 76421358,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Ariana',
    lastName: 'Ramos Delgadillo',
    email: 'ariana@gmail.com',
    carnet: '9312475',
    phone: 75621489,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Leonardo',
    lastName: 'Arce Vargas',
    email: 'leo@gmail.com',
    carnet: '8514623',
    phone: 78412395,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Micaela',
    lastName: 'Lopez Reyes',
    email: 'mica@gmail.com',
    carnet: '8213654',
    phone: 71658423,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Andres',
    lastName: 'Rivera Zapata',
    email: 'andres@gmail.com',
    carnet: '7814562',
    phone: 78361452,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Daniela',
    lastName: 'Paz Gutierrez',
    email: 'dani@gmail.com',
    carnet: '9512468',
    phone: 75983214,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Matias',
    lastName: 'Silva Roca',
    email: 'matias@gmail.com',
    carnet: '9612354',
    phone: 78542196,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Isabella',
    lastName: 'Fernandez Rocha',
    email: 'isabella@gmail.com',
    carnet: '8741259',
    phone: 78954126,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Sebastian',
    lastName: 'Lima Herrera',
    email: 'sebastian@gmail.com',
    carnet: '9124785',
    phone: 79124578,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Antonella',
    lastName: 'Mejia Castro',
    email: 'antonella@gmail.com',
    carnet: '8547961',
    phone: 76895412,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Franco',
    lastName: 'Gutierrez Lima',
    email: 'franco@gmail.com',
    carnet: '8427963',
    phone: 77985412,
    password: 'password123',
    profilePicture: '',
  },
  {
    name: 'Renata',
    lastName: 'Morales Rojas',
    email: 'renata@gmail.com',
    carnet: '9321475',
    phone: 77584129,
    password: 'password123',
    profilePicture: '',
  },
];
